trigger:
  branches:
    include:
    - main
    - production
  paths:
    include:
    - src/fedora/*
pr: none

resources:
  repositories:
  - repository: InternalVersionsRepo
    type: github
    endpoint: dotnet
    name: dotnet/versions

variables:
- template: variables/common.yml
- name: imageBuilder.pathArgs
  value: --path 'src/fedora/*'

stages:
- template: ../common/templates/stages/dotnet/build-test-publish-repo.yml
  parameters:
    internalProjectName: ${{ variables.internalProjectName }}
    publicProjectName: ${{ variables.publicProjectName }}
    ${{ if eq(variables['System.TeamProject'], 'internal') }}:
      customCopyBaseImagesInitSteps:
      - template: ../../../pipelines/steps/set-base-image-override-options.yml
        parameters:
          variableName: customCopyBaseImagesArgs
          dockerfileOs: fedora
          baseOverrideRegistry: $(overrideRegistry) # Comes from DotNet-Docker-Common variable group
      - template: ../../../pipelines/steps/set-base-image-override-options.yml
        parameters:
          variableName: imageBuilderBuildArgs
          dockerfileOs: fedora
          baseOverrideRegistry: $(overrideRegistry) # Comes from DotNet-Docker-Common variable group
